notifications:
  email: false

dist: xenial

sudo: required

addons:
  postgresql: 10

services:
  - postgresql

env:
  global:
    - DATABASE_URL=postgresql://travis

language: python

cache: pip

python:
  - 3.6

matrix:
  fast_finish: true

before_install:
  - travis_retry pip install --upgrade pip setuptools
  - travis_retry pip install coveralls

install:
  - travis_retry pip install -r requirements-dev.txt

before_script:
  - python -c 'from app import db; db.create_all()'

script:
  - ./run-tests.sh

after_success:
  - travis_retry coveralls

deploy:
  provider: heroku
  api_key:
    secure: DXtZTYChQOm6/hGww9RtwnwAuFtKE8J38kTxM8HhTpmFVCuWNZNt5IymwbeK3E7K9OKCbMwX8zozX9ARUXToW9Ox/8WUslZ11Ghr/LVoQiqDbMSeNjUr4uK3oPfoDHlwLVTF60/0TfA0WfqHfFciNFSk+WsePOU/HRId8kPMcV4jwN1FSCD9kNfYdg8jmjDk3z0F96+c+4tjz+Y2QA+g7xnCkwfYlfh1rd+5aAOKI1/lkxx0/daOBKJGM1Ow4f8f1M1FenuPZyCQWnS6nDXShE/UUU/8J3L3IKPRh4H1oNA6r5HkGE4Xp83h66byV2u2c+nfVOFejENHrzx4tPeYkm+CqR+MaaQhJTrqEWEcXaOmkjBluevmQgcuq7lWQZ/RXV0pailndDOOdbrDpqaejn5aaSzIeUm90lffszisSJ1b7wwwewcD8SvL3lgB9Jmq8ujcaXamqQSoq9y7QFg+M1FRCDbQfyloGW89o8QYrere7wUagLrZxCNweIWqgUNWGVHmCdzpezaX2TUHWIh6bQNQNFa8KbSK+zVrPFVxwg3jhIgzZTKlNWOCnrjp+TzFWM0WlU/QjY1p7Nv2D9hIspczT/osNW5lFDlK+qDjD/R8IFOacK7oE72KvLC9gzJh7eyI4fII4Q1gSavOBh/puJymDCGUXH11gCZjiuiwZJ8=
