notifications:
  email: false

dist: xenial

sudo: required

addons:
  postgresql: 10

services:
  - postgresql

env:
  global:
    - DATABASE_URL=postgresql://travis

language: python

cache: pip

python:
  - 3.6

matrix:
  fast_finish: true

before_install:
  - travis_retry pip install --upgrade pip setuptools
  - travis_retry pip install coveralls

install:
  - travis_retry pip install -r requirements-dev.txt

before_script:
  - python -c 'from app import db; db.create_all()'

script:
  - ./run-tests.sh

after_success:
  - travis_retry coveralls
