notifications:
  email: false

dist: xenial

sudo: required

addons:
  postgresql: 10

services:
  - postgresql

env:
  global:
    - DATABASE_URL=postgresql://travis

language: python

cache: pip

python:
  - 3.6

matrix:
  fast_finish: true

before_install:
  - travis_retry pip install --upgrade pip setuptools
  - travis_retry pip install coveralls

install:
  - travis_retry pip install -r requirements-dev.txt

script:
  - ./run-tests.sh

after_success:
  - travis_retry coveralls

deploy:
  provider: heroku
  api_key:
    secure: lCl7CEvchLCaYDGqW/cUqltbUb5rk+YhYZ3gSz3k/HTj5Fn/Z10nOTre1mSmTeuVOLw+fnf4SC6LOcHmt+mBaAK7Bi7n7oLlL1I2t3isrRlUbYY+F6X36hCTdi2SyQp2hkKIXzE3TI6kqpsI8WaLIcGYrJO1L0cJ/OP9xl8yhBRnKxvIMltNjPHXwcRJeJk3jctOHLE66jH64F3FBpoTqxcognczuxUAn2fGM01CBOZ/5vz9c8ODNxxVds7xm9xv6No0DTAueC7HN33491YgwOwDDKvEJ8Zp4yB9mmEjNZCqvvdQdB0n6J5M7UGUG1KGaBnmLLamTrpwLaQraRQrydqVWfPMoxXb3OtAGe+UeVhwiKTY0DSLh1SN1r44Lcz2eWMY+vwEGxwfpZzfsq9fkzKyIAGWmJmLbnb6KXVp6ESR+xcy+jq3nae3fxTR4bkEwrd06E3CiCSRRcYimgfytvthT/8/VpBH59R1kwf38MGgXzvJfZCmCBYyM3Qx30cauikNk6TfpMlleInR9jibGXDcQKVdP5vLnzw2z60X2666VZuxQIzW/GtSefY+kY9mwOE9NzazeZmuHltpQEkwLN9T3OnHNxgBATKqD/h3JXFWcer36zPXKfWrZSjsQ5ISZTbghazaS+oqh5s9ervhR4zgCPIDoI08W8x55QiU/44=
